"use client"
// This component was generated by @sitecore-search/cli on Tue Aug 27 2024 11:45:52 GMT+0200 (Central European Summer Time)
import { useRouter } from 'next/navigation'

import type { ActionProp, ItemClickedAction } from '@sitecore-search/react';
import { ArticleCard } from '@sitecore-search/ui';
import Image from 'next/image'
import { DEFAULT_IMG_URL } from '@/app/_data/customizations';

type ArticleCardItemCardProps = {
  className?: string;
  displayText?: boolean;
  article: any;
  onItemClick: ActionProp<ItemClickedAction>;
  index: number;
};

const ArticleHorizontalItemCard = ({ className = '', article, onItemClick, index }: ArticleCardItemCardProps) => {
  const router = useRouter();
  const validImageUrl = article.image_url?.trim() ? article.image_url : DEFAULT_IMG_URL;
  console.log(article)
  return (
    <ArticleCard.Root
      key={article.id}
      className={`group flex flex-row my-4 flex-nowrap max-h-52 w-full relative border border-gray-200 dark:border-gray-600 rounded-md hover:shadow-lg hover:transition-all hover:ease-linear	hover:duration-300 focus-within:transition-all focus-within:ease-linear focus-within:duration-300 focus-within:hover:shadow-lg ${className} bg-white rounded-lg shadow-sm border p-6 transition-shadow `}
    >
       {article.image_url &&
      <div className="w-[25%] flex-none overflow-hidden bg-gray-200 rounded">
        <Image
          src={validImageUrl}
          className="h-full w-full object-cover object-center lg:h-full lg:w-full rounded"
          alt='alt'
          width={500}
          height={115}
        />
      </div>}
      <div className="pl-4 grow flex-col">
        <a
          className="focus:outline-indigo-500"
          href={article.url}
          onClick={(event) => {
            event.preventDefault();
            onItemClick({
              id: article.id,
              index,
              sourceId: article.source_id,
            });
            router.push(`/detail/${article.id}`);
          }}
        >
          <span aria-hidden="true" className="absolute inset-0"></span>
          <ArticleCard.Title className="text-lg font-semibold text-gray-900 mb-2">{article.name || article.title}</ArticleCard.Title>
        </a>
        <ArticleCard.Subtitle className="mt-3 text-sm text-gray-600 dark:text-gray-300 h-[100px] overflow-hidden line-clamp-2">
          {article.description}
        </ArticleCard.Subtitle>
      </div>
    </ArticleCard.Root>
  );
};
export default ArticleHorizontalItemCard;
